const sampleData = {
  products: [
    {
      id: 1,
      name: "مبل مدرن",
      slug: "طراحی زیبا و کیفیت عالی",
      category: "مبل",
      description: "طراحی زیبا و کیفیت عالی",
      images: ["/images/products/p1.jpg", "/images/products/p2.jpg"],
      price: 5_000_000,
      brand: "Polo",
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: "banner-1.jpg",
    },
    {
      id: 2,
      name: "مبل مدرن",
      slug: "طراحی زیبا و کیفیت عالی",
      category: "مبل",
      description: "طراحی زیبا و کیفیت عالی",
      images: ["/images/products/p1.jpg", "/images/products/p2.jpg"],
      price: 5_000_000,
      brand: "Polo",
      rating: 4.5,
      numReviews: 10,
      stock: 0,
      isFeatured: true,
      banner: "banner-1.jpg",
    },
    {
      id: 3,
      name: "مبل مدرن",
      slug: "طراحی زیبا و کیفیت عالی",
      category: "مبل",
      description: "طراحی زیبا و کیفیت عالی",
      images: ["/images/products/p3.jpg", "/images/products/p4.jpg"],
      price: 10_000_000,
      brand: "Polo",
      rating: 4.5,
      numReviews: 10,
      stock: 10,
      isFeatured: true,
      banner: "banner-1.jpg",
    },
    {
      id: 4,
      name: "مبل مدرن",
      slug: "طراحی زیبا و کیفیت عالی",
      category: "مبل",
      description: "طراحی زیبا و کیفیت عالی",
      images: ["/images/products/p1.jpg", "/images/products/p2.jpg"],
      price: 6_000_000,
      brand: "Polo",
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: "banner-1.jpg",
    },
  ],
  users: [
    {
      name: "Ali",
      email: "ali@example.com",
      password: "12345678",
      role: "admin",
    },
  ],

  // blogs
};

export default sampleData;
